// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOi6zme62Sw5iA-bfWKPCQJIqcWj6JN18',
    appId: '1:879875244318:web:c7aeb09acbc647037c490f',
    messagingSenderId: '879875244318',
    projectId: 'up-todo-29a58',
    authDomain: 'up-todo-29a58.firebaseapp.com',
    storageBucket: 'up-todo-29a58.appspot.com',
    measurementId: 'G-5FCX38STHT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIOV_wY-FzH7Z3Gx3AOISgPgnpIzE5o4w',
    appId: '1:879875244318:android:0d976b52fd627a8f7c490f',
    messagingSenderId: '879875244318',
    projectId: 'up-todo-29a58',
    storageBucket: 'up-todo-29a58.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy1L-LrmiTBLlQwmewbvG30h6KejR-Dyo',
    appId: '1:879875244318:ios:f9f75141e7983a647c490f',
    messagingSenderId: '879875244318',
    projectId: 'up-todo-29a58',
    storageBucket: 'up-todo-29a58.appspot.com',
    iosBundleId: 'com.example.upTodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy1L-LrmiTBLlQwmewbvG30h6KejR-Dyo',
    appId: '1:879875244318:ios:709d625dec60e2b07c490f',
    messagingSenderId: '879875244318',
    projectId: 'up-todo-29a58',
    storageBucket: 'up-todo-29a58.appspot.com',
    iosBundleId: 'com.example.upTodo.RunnerTests',
  );
}
